### ISSUE TITLE
Categorising Players by Country

### ISSUE THREAD

**Issue by SRP457** [HackerSpace-PESU/Best11-Fantasycricket#10]
**Describe the Issue:**
The current data has players in no particular order or pattern. To allow for other exploratory data analysis, categorising players by country would be useful.

**Solution:**
Categorise the players in the data folder by country and update them in another folder named **categorised** under the data folder.

Comment if you would like to work on it.

**Comment by amoghku02** [comment]
Hey, I would like to work on this issue for hacktoberfest.
Can you assign it to me?

**Comment by lucasace** [comment]
yea go ahead assigning it to @amoghku02

**Comment by amoghku02** [comment]
PR for the issue is made. Please review.
