### ISSUE TITLE
Better interface

### ISSUE THREAD

**Issue by SammithSB** [HackerSpace-PESU/Best11-Fantasycricket#15]
**Issue**
We are looking for a better front-end for our GUI, no backend changes expected
**Solution**
We are not expecting anything complex, any kind of significant improvements to the present model is welcome.

**Comment by adavijit** [comment]
@SammithSB  assign it to me

**Comment by lucasace** [comment]
Assigned to @adavijit ! Thanks for contributing

**Comment by lucasace** [comment]
@adavijit Since we planned to change the framework to FastApi , I recommend you only work towards the frontend part of the interface

**Comment by milanmandal** [comment]
I can work on the improvement
