### ISSUE TITLE
[FEATURE] Add a function for averages

### ISSUE THREAD

**Issue by lucasace** [HackerSpace-PESU/Best11-Fantasycricket#18]
**Describe the issue**
We would like to add statistics such as [batting average](https://en.wikipedia.org/wiki/Batting_average_(cricket)), [bowling average](https://en.wikipedia.org/wiki/Bowling_average) to our dataset

**Solution**
To do this , we would like you to add two functions in a file called average.py, batting
_average and bowling_average, and implement them. 

**Test**
run both of them and check if it updates the dataset

Note: While making a PR dont send it in with the updated dataset, that will be done by the maintainers only, just write the functions in the file as of now

Comment if you would like to work on it

**Comment by matheuscr30** [comment]
I want to help u. Can u assign it to me?

**Comment by lucasace** [comment]
Yea go ahead , Assigning it to @matheuscr30

**Comment by mishatheking** [comment]
Can I get a shot at it

**Comment by lucasace** [comment]
@mishatheking sorry but it already has been assigned,
Maybe if there's inactivity on this issue, it will be reassigned
Meanwhile check out other issues or watch for more issues

**Comment by matheuscr30** [comment]
@mishatheking You can do it, some unexpected events happened here and I'll not be able to do this

**Comment by lucasace** [comment]
@mishatheking do you wanna take this up?

**Comment by abhisinha2001** [comment]
Can I please take this up?

**Comment by lucasace** [comment]
Yea sure! assigning it to @abhisinha2001
