### ISSUE TITLE
[recommendation] Change from Flask to fastapi

### ISSUE THREAD

**Issue by scientes** [HackerSpace-PESU/Best11-Fantasycricket#21]
Fastapi is a python framework designed for building apis:
https://fastapi.tiangolo.com/
it simplifies things, uses stuff like pydantic for input verification and has automatic Openapi (swagger) support and much more nice treats

**Comment by lucasace** [comment]
Heyy, @scientes thanks for the recommedation , ill surely look into this

**Comment by lucasace** [comment]
Hey thanks for the suggestion! We will be implementing it
