### ISSUE TITLE
[BUG] Fix changes after PR #26

### ISSUE THREAD

**Issue by lucasace** [HackerSpace-PESU/Best11-Fantasycricket#27]
**Describe the bug**
In PR #26 , the model fails due to updated folder names, It needs to fixed before merging it into master

**To Reproduce**
run app.py or check .py from the issue-25 branch only

**Expected behavior**
It must work the same as before. All changes must be done in the issue-25 branch only

**Additional context**
Not much work, wherever there is zip,zip2,bowl or wk, it just needs to be updated to 'zip/ODI' or 'zip2/ODI' and so on

**Comment by egurnick** [comment]
Hi, I'll fix these bugs. Please assign the issue to me
