### ISSUE TITLE
Ignore retired players

### ISSUE THREAD

**Issue by lucasace** [HackerSpace-PESU/Best11-Fantasycricket#41]
**Describe the bug**
It is evident that retired players don't play anymore. The webcrawler still includes them which needs to be filtered

**To Reproduce**
1. Follow the instructions in [README.md](https://github.com/HackerSpace-PESU/Best11-Fantasycricket/blob/feature-webcrawler/crawler/README.md) and notice once it starts collecting players. It can also be noticed in `data_crawler/ids_names.csv`. 

 
**Possible Solution**
The solution :
     in `cralwer/cricketcrawler/spiders/howstat.py` , in function `parse_player`
 
```python
if retired == False:
          yield PlayerItem(name=url[url.find("?PlayerID=")+10:],gametype=gametype,folder=".",longname=name,retired=retired)
```

**Screenshots**
![Screenshot from 2020-11-14 13-51-43](https://user-images.githubusercontent.com/54945757/99143431-6317af80-2683-11eb-8bf4-a55502331148.png)

**Desktop (please complete the following information):**
 - Version [`master`]

**Comment by chriswolfdesign** [comment]
I'd be willing to give this a try.  Just to clarify: you don't want players to show up when they are retired?

**Comment by lucasace** [comment]
Yea, as you can notice in the id_names.csv there retired column some of
them are true. Those players should not be considered by the crawler

**Comment by scientes** [comment]
note from my side:
i included the retired as im not sure that all i mark as retired actually are. Also you might notice that a player can ocurr up to three times in the csv due to there being a page for each player on test,T20,ODI if they plaeyed in them. there could be the possibility that a player might not be playing in one of those catergories but is still active in another.

**Comment by lucasace** [comment]
> i included the retired as im not sure that all i mark as retired actually are.

Could you elaborate on this? I didnt quite get you

> Also you might notice that a player can ocurr up to three times in the csv due to there being a page for each player on test,T20,ODI if they plaeyed in them. there could be the possibility that a player might not be playing in one of those catergories but is still active in another.

I was actually gonna change this to one time when i got the time and  delete the `gametype` column entirely. If he isnt active in the other formats , That should'nt matter cause his records will simply not be present in the respective format's folder. That shouldnt cause any problems.

**Comment by scientes** [comment]
> 
> 
> > i included the retired as im not sure that all i mark as retired actually are.
> 
> Could you elaborate on this? I didnt quite get you
> 
i havent verfied that the data in the retired column is correct and that every player with retired=True is actually retired and i haven't checked if this also is the same for every gametype (meaning that when player is retired he is marked as such in evry gametype)

**Comment by lucasace** [comment]
> > > i included the retired as im not sure that all i mark as retired actually are.
> > 
> > 
> > Could you elaborate on this? I didnt quite get you
> 
> i havent verfied that the data in the retired column is correct and that every player with retired=True is actually retired and i haven't checked if this also is the same for every gametype (meaning that when player is retired he is marked as such in every gametype)

Aah , then this issue can be dangerous if fixed, Ill verify this asap
Ill add a wontfix label for now
