### ISSUE TITLE
[FEATURE] Add batting crawler to the webcrawler

### ISSUE THREAD

**Issue by lucasace** [HackerSpace-PESU/Best11-Fantasycricket#42]
**Is your feature request related to a problem? Please describe.**
The crawler currently only crawls for new players , and match ids. The web crawler also needs to crawl for batting stats

**Describe the solution you'd like**
<del>A function similar to `parse_player` and `parse_scorecard`</del> Extend function `parse_scorecard` in `crawler/cricketcrawler/cricketcrawler/spiders/howstat.py` to batting and get the following
* runs
* no of 4s and 6s
* strike rate

Refer Dataset.md to understand the matchcodes and playercodes

**Additional context**
Crawler can be found in `feature-webcrawler` branch of the repo. Crawler is built using `[scrapy](https://scrapy.org/)`

**Comment by scientes** [comment]
to reduce requests i'd advise to not make a new function, but to just extend the parse_scorecard function so that batting etc. is collected, if the information is on the same page as the matchid stuff. (but maybe im wrong) if anybody has questions about scrapy and its working i'll help but my knowledge of cricket is insufficient to say the least.

**Comment by lucasace** [comment]
Ahh right that sounds better , I had a few questions myself. I'll be sure to ask you those once I get free. Im quite busy this and next week myself.

**Comment by lucasace** [comment]
> to reduce requests i'd advise to not make a new function, but to just extend the parse_scorecard function

Ill make the change for this

**Comment by lucasace** [comment]
Closed by commit [`6272197`](https://github.com/HackerSpace-PESU/Best11-Fantasycricket/commit/6272197a3e4a607abc1302df0a635c7297fee14b)

Point 8
