### ISSUE TITLE
[FEATURE] Add bowling crawler to the webcrawler

### ISSUE THREAD

**Issue by lucasace** [HackerSpace-PESU/Best11-Fantasycricket#43]
**Is your feature request related to a problem? Please describe.**
The crawler currently only crawls for new players , and match ids. The web crawler also needs to crawl for batting stats

**Describe the solution you'd like**
Extend function `parse_scorecard` in `crawler/cricketcrawler/cricketcrawler/spiders/howstat.py` to bowling and get the following
* wickets
* Overs
* Maidens
* Economy

Refer Dataset.md to understand the matchcodes and playercodes

**Additional context**
Crawler can be found in `feature-webcrawler` branch of the repo. Crawler is built using `[scrapy](https://scrapy.org/)`

**Comment by lucasace** [comment]
Closed by commit `[6272197](https://github.com/HackerSpace-PESU/Best11-Fantasycricket/commit/6272197a3e4a607abc1302df0a635c7297fee14b)`

Point 8

**Comment by scientes** [comment]
nice

**Comment by scientes** [comment]
most interestingly i'm still not a contributor ^^
(not thats important to me)

**Comment by lucasace** [comment]
> most interestingly i'm still not a contributor ^^
> (not thats important to me)

Haha! I was just merging the feature-webcrawler and master when you sent this
You are now!!

Sorry for the significant delay on it xD

**Comment by scientes** [comment]
Thx :blush:
