### ISSUE TITLE
Add SEO to HTML templates

### ISSUE THREAD

**Issue by scientes** [HackerSpace-PESU/Best11-Fantasycricket#50]
Good Resource: https://developers.google.com/search/docs/beginner/seo-starter-guide?hl=en

**Comment by lucasace** [comment]
Closed by [`6ad45ff`](https://github.com/HackerSpace-PESU/Best11-Fantasycricket/pull/49/commits/6ad45ff3a9f2405948c258f2ba762d3c61d43963)
