### ISSUE TITLE
Test Player Records Required

### ISSUE THREAD

**Issue by SRP457** [HackerSpace-PESU/Best11-Fantasycricket#7]
**Describe the Issue:**
The current model uses player data from ODI matches only. Adding Test matches would improve the usability of the model.

**Solution:**
Employ a web-scraper to scrape player records from **howstat.com** for test matches and update them in the data folder.
Ensure the scraped data is in the same format as the files in the data folder.

Comment if you would like to work on it.

**Comment by lucasace** [comment]
I am linking this issue to issue #3 , as it can be completed simultaneously

**Comment by lucasace** [comment]
Closed! Thanks to @scientes
