### ISSUE TITLE
No match found

### ISSUE THREAD

**Issue by basavaraja-v** [HackerSpace-PESU/Best11-Fantasycricket#72]
Getting, There are no matches scheduled for the next 24 hours!.
IPL 2022 started but it is showing the above result. can anyone help on this.

**Comment by roysti10** [comment]
Heyy, The website is down for a while 
We will restart it soon , currently all the maintainers are busy and hence will take some time in restarting the project

We request your patience 
Do feel free to send a PR if you think you can fix it

Thank You!
